language: php

php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

git:
  depth: false

install:
  - composer update --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpstan analyse src -c phpstan.neon --level=max --no-progress -vvv
  - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
